### ISSUE TITLE
Documentation of provider logs

### ISSUE THREAD

**Issue by dunderrrrrr** [golemfactory/golem-docs#279]
I recently got my provider up and running. Works great. However, I dont really understand what all the output in `.local/share/ya-provider/ya-provider_rCURRENT.log` really means. It seems like these messages are not in the documentation.

Some of the logs are self explanatory, but others are rather difficult to understand imo.

Here are some lines from my logs.

- `Negotiator component 'DebitNoteInterval' is still negotiating Proposal...`
- `Negotiator component 'PaymentTimeout' is still negotiating Proposal...`
- `Decided to CounterProposal...`
- `Got proposal...`
- `Resubscribing subscription...`
- `Unsubscribing 1 offer(s)`
- `Subscribed offer. Subscription id ...`
- `Failed to unsubscribe offers from the market: HTTP error requesting DELETE http://...`
- `Can't query market events. Error: HTTP error requesting GET http://... 404 Not Found; msg:...`
- `Error sending invoice: HTTP error requesting POST http://...`

Wouldn't it be nice so have all, or some, of these messages in the docs? I'd be happy to att them [here](https://docs.golem.network/docs/providers/provider-faq#where-can-i-find-yagna-logs) somewhere. I just need some help figuring out what of these lines mean.

**Comment by cryptobench** [comment]
Hey bud! Thanks for the issue and PR. 

You're very much right that it's a topic that's missing in our documentation - so thank you for pointing that out! 

We will sit down and take a look at this.

**Comment by dunderrrrrr** [comment]
Awesome, thanks! Let me know if you need any assistance.

**Comment by cryptobench** [comment]
Thanks bud, much appreciated. Will do! :-)

**Comment by jalas167** [comment]
added under: https://docs.golem.network/docs/providers/understanding-logs#understanding-your-golem-provider-logs
