### ISSUE TITLE
Error: Local service error: Transfer error: Send error: send failed because receiver is gone. Stdout: undefined. Stderr: undefined

### ISSUE THREAD

**Issue by rogwild** [golemfactory/golem-docs#8]
[Documentation Page](https://docs.golem.network/creators/javascript/quickstart/)

An error in `await ctx.uploadFile("./task.js", "/golem/work/task.js");`. 

The package `529f7fdaf1cf46ce3126eb6bbcd3b213c314fe8fe884914f5d1106d4` doesn't have a VOLUME in  `/golem/work`. That's why `node index.js` throws an error `Error: Local service error: Transfer error: Send error: send failed because receiver is gone. Stdout: undefined. Stderr: undefined`.

If change `await ctx.uploadFile("./task.js", "/golem/work/task.js");` to `await ctx.uploadFile("./task.js", "/golem/input/task.js");` and `const result = await ctx.run("node", ["/golem/work/task.js"]);` to `const result = await ctx.run("cd ../input && node task.js");` starts working good.

```js
import { TaskExecutor } from "yajsapi";

(async () => {
  const executor = await TaskExecutor.create("529f7fdaf1cf46ce3126eb6bbcd3b213c314fe8fe884914f5d1106d4");
  const result = await executor.run(async (ctx) => {
      await ctx.uploadFile("./task.js", "/golem/input/task.js");
      const result = await ctx.run("cd ../input && node task.js");
  });
  await executor.end();

  console.log("Task result:", result);
})();
```

**Comment by jalas167** [comment]
fixed, image hash replaced with a new one, 
return statement added
